{{- define "helm-framework.deployment.job" -}}
{{- $root := . -}}
{{- $state := dict "rendered" false -}}
{{- range $index, $job := .Values.jobs }}
{{- if $job.enabled }}
{{- if $state.rendered }}
---
{{- end }}
{{- $_ := set $state "rendered" true }}
{{- $jobName := $job.name | default (printf "job-%d" $index) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-framework.fullname" $root }}-{{ $jobName }}
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
  labels:
    job: {{ include "helm-framework.fullname" $root }}-{{ $jobName }}
    {{- include "helm-framework.labels" $root | nindent 4 }}
spec:
  backoffLimit: {{ $job.backoffLimit | default 6 | int }}
  template:
    metadata:
      annotations:
        {{- include "helm-framework.job.podAnnotations" $root | nindent 8 }}
      labels:
        {{- include "helm-framework.job.podLabels" $root | nindent 8 }}
    spec:
      {{- if $root.Values.imagePullSecrets }}
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "helm-framework.serviceAccountName" $root }}
      {{- with $root.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ $job.restartPolicy | default "OnFailure" }}
      {{- if (($root.Values.initContainer).caBundle).enabled }}
      initContainers:
        {{- include "helm-framework.job.caBundleInit" $root | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $root.Chart.Name }}
          {{- with $root.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ required "Image repository is required!" (($job.image).repository | default ($root.Values.image).repository) }}:{{ ($job.image).tag | default ($root.Values.image).tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ ($job.image).pullPolicy | default "IfNotPresent" }}
          {{- if $job.args }}
          args:
            {{- toYaml $job.args | nindent 12 }}
          {{- end }}
          {{- if $job.command }}
          command:
            {{- toYaml $job.command | nindent 12 }}
          {{- end }}

          {{- if or $root.Values.envVars $job.envVars }}
          env:
            {{- with $root.Values.envVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $job.envVars }}
            {{- tpl (toYaml .) $root | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if or $root.Values.envVarsFromSecret $job.envFrom }}
          envFrom:
            {{- if $root.Values.envVarsFromSecret }}
            - secretRef:
                name: {{ include "helm-framework.secret-env-name" $root }}
                optional: false
            {{- end }}
            {{- with $job.envFrom }}
            {{- tpl (toYaml .) $root | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- $res := $job.resources | default $root.Values.resources }}
          {{- include "helm-framework.job.resources" (dict "root" $root "resources" $res) | trim | nindent 10 }}
          volumeMounts:
            {{- with (include "helm-framework.job.commonVolumeMounts" $root | trim) }}
            {{- . | nindent 12 }}
            {{- end }}
          {{- if $root.Values.volumeMounts }}
            {{- tpl (toYaml $root.Values.volumeMounts) $root | nindent 12 }}
          {{- end }}
          {{- if $job.volumeMounts }}
            {{- tpl (toYaml $job.volumeMounts) $root | nindent 12 }}
          {{- end }}
      volumes:
        {{- with (include "helm-framework.job.commonVolumes" $root | trim) }}
        {{- . | nindent 8 }}
        {{- end }}
      {{- if $root.Values.volumes }}
        {{- tpl (toYaml $root.Values.volumes) $root | nindent 8 }}
      {{- end }}
      {{- if $job.volumes }}
        {{- tpl (toYaml $job.volumes) $root | nindent 8 }}
      {{- end }}
      {{- with (include "helm-framework.job.scheduling" $root | trim) }}
      {{- . | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
