#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  buildValuesContractMarkdown,
  buildMigrationSkillMarkdown,
  buildMigrationPlaybookMarkdown,
} from './generate-migration-skill.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');

// Deliberate exceptions to the values-contract drift guard (e.g. a
// parent-chart-supplied `global`). Empty today — see
// docs/superpowers/specs/2026-07-29-helm-framework-migration-check-design.md.
const CONTRACT_ALLOWLIST = [];

export function parseVersionArg(argv) {
  const idx = argv.indexOf('--version');
  if (idx === -1 || !argv[idx + 1]) {
    throw new Error('Usage: generate-skill.mjs --version <X.Y.Z>');
  }
  return argv[idx + 1];
}

export function extractChartName(chartYamlContent) {
  const match = chartYamlContent.match(/^name:\s*["']?([^"'\s]+)["']?/m);
  if (!match) {
    throw new Error('Could not find "name:" in Chart.yaml');
  }
  return match[1];
}

export function extractSections(valuesYamlContent) {
  const lines = valuesYamlContent.split('\n');
  const sections = [];
  for (let i = 0; i < lines.length - 2; i++) {
    if (
      /^# =+$/.test(lines[i]) &&
      /^# .+$/.test(lines[i + 1]) &&
      /^# =+$/.test(lines[i + 2])
    ) {
      sections.push(lines[i + 1].replace(/^# /, '').trim());
    }
  }
  return sections;
}

export function extractValuesTable(readmeContent) {
  const marker = '## Values';
  const idx = readmeContent.indexOf(marker);
  if (idx === -1) {
    throw new Error('Could not find "## Values" section in README.md');
  }
  let table = readmeContent.slice(idx);
  // Drop helm-docs' own "Autogenerated from chart metadata..." footer, which
  // starts with a horizontal-rule line — it documents helm-docs, not a value.
  const footerMatch = table.match(/\n-{3,}\n/);
  if (footerMatch) {
    table = table.slice(0, footerMatch.index);
  }
  return table.trim();
}

export function buildSkillMarkdown({ chartName, version, sections }) {
  const sectionList = sections.map((s) => `- ${s}`).join('\n');
  return `---
name: "helm-framework"
description: "Scaffold and configure Helm charts that depend on the ${chartName} library chart. Use when adding ${chartName} as a Helm dependency, writing values.yaml for a chart built on it, or looking up what a value controls."
---

# ${chartName}

## What this skill does

Helps you add \`${chartName}\` (a Helm **library chart**) as a dependency of
your own chart, wire up the single template include it needs, and configure
it correctly through \`values.yaml\`.

Consumers never copy the library's templates — they \`include\` one entry
point and configure everything through their own \`values.yaml\`.

## Quick start

1. Add the dependency to your chart's \`Chart.yaml\`:

\`\`\`yaml
dependencies:
  - name: ${chartName}
    version: "${version}"
    repository: "oci://ghcr.io/k8s-stuff"
\`\`\`

   Or, using the classic Helm repository instead of OCI:

\`\`\`yaml
dependencies:
  - name: ${chartName}
    version: "${version}"
    repository: "https://k8s-stuff.github.io/${chartName}"
\`\`\`

2. Run \`helm dependency update\`.
3. Add one line to a template in your chart (e.g. \`templates/deployment.yaml\`):

\`\`\`yaml
{{ include "${chartName}.deployment.global" . }}
\`\`\`

4. Configure everything through your chart's own \`values.yaml\` — copy in
   only the keys you need from \`resources/values-reference.md\`.

## Values reference

\`resources/values-reference.md\` has the full, generated reference for
every configurable value, grouped into these sections:

${sectionList}

## Worked example

\`resources/example-chart.md\` has a complete, working chart
(\`Chart.yaml\`, \`values.yaml\`, and the single-line template) copied from
this library's own test-template chart.

## Migrating an existing chart?

If you're moving a chart with hand-rolled templates onto \`${chartName}\`
rather than starting fresh, see the sibling \`${chartName}-migration\` skill —
it covers regression checking and orphaned-value cleanup.
`;
}

export function buildExampleChartMarkdown({ chartYaml, valuesYaml, deploymentTemplate }) {
  return `# Example: a chart depending on helm-framework

Copied from \`helm-framework-test-template\`, the library's own working
example chart.

## Chart.yaml

> The \`dependencies:\` block below uses a local \`file://\` path specific to
> this monorepo — copy the OCI or classic-repo dependency snippet from the
> Quick start section above instead.

\`\`\`yaml
${chartYaml.trim()}
\`\`\`

## values.yaml

\`\`\`yaml
${valuesYaml.trim()}
\`\`\`

## templates/deployment.yaml

\`\`\`yaml
${deploymentTemplate.trim()}
\`\`\`
`;
}

/**
 * Top-level `.Values.<name>` keys read anywhere across a set of template
 * sources. `templateSources` is an array of file contents (one string per
 * template file) — they are joined before scanning, so a single
 * concatenated string works identically. This only catches literal
 * `.Values.X` references; access through helper indirection (e.g.
 * `include "helm-framework.values.service.port"`) is invisible to this scan,
 * which is why only the *top-level* result is treated as authoritative.
 */
export function extractValuesReadSet(templateSources) {
  const combined = Array.isArray(templateSources) ? templateSources.join('\n') : templateSources;
  const re = /\.Values\.([A-Za-z0-9_]+)/g;
  const found = new Set();
  let match;
  while ((match = re.exec(combined)) !== null) {
    found.add(match[1]);
  }
  return [...found].sort();
}

/**
 * Declared key paths (dotted, nested) from a values.yaml, derived purely
 * from indentation — no YAML parsing. Comments and blank lines are
 * skipped. List items (`- foo` / `- name: x`) are not descended into:
 * sequence entries aren't stable key paths, so only the key that holds the
 * list (e.g. `ingress.hosts`) is recorded, never anything inside an entry.
 */
export function extractValueTree(valuesYamlContent) {
  const lines = valuesYamlContent.split('\n');
  const paths = new Set();
  const stack = []; // { indent, path }
  let skipIndent = null; // set while scanning inside a list item's subtree

  for (const rawLine of lines) {
    if (!rawLine.trim()) continue;
    const indent = rawLine.length - rawLine.trimStart().length;
    const trimmed = rawLine.trim();
    if (trimmed.startsWith('#')) continue;

    if (skipIndent !== null) {
      if (indent >= skipIndent) continue;
      skipIndent = null;
    }

    if (trimmed === '-' || trimmed.startsWith('- ')) {
      skipIndent = indent;
      continue;
    }

    const keyMatch = trimmed.match(/^([A-Za-z0-9_]+):/);
    if (!keyMatch) continue;

    while (stack.length && stack[stack.length - 1].indent >= indent) {
      stack.pop();
    }
    const parent = stack.length ? stack[stack.length - 1].path : null;
    const path = parent ? `${parent}.${keyMatch[1]}` : keyMatch[1];
    paths.add(path);
    stack.push({ indent, path });
  }

  return [...paths].sort();
}

/**
 * The values-contract drift guard. Throws when the top-level read-set
 * (what templates actually read) and the top-level declared set (what
 * values.yaml documents) disagree in either direction. Both directions are
 * real bugs — see the thrown message for why. Keys in `allowlist` are
 * exempt from both directions. Returns nothing on success.
 */
export function assertContractConsistency(readSet, declaredTopLevel, allowlist = []) {
  const allow = new Set(allowlist);
  const read = new Set(readSet);
  const declared = new Set(declaredTopLevel);

  const readButUndeclared = [...read].filter((k) => !declared.has(k) && !allow.has(k)).sort();
  const declaredButUnread = [...declared].filter((k) => !read.has(k) && !allow.has(k)).sort();

  if (readButUndeclared.length === 0 && declaredButUnread.length === 0) {
    return;
  }

  const parts = [];
  if (readButUndeclared.length) {
    parts.push(
      `Templates read ${readButUndeclared.length} top-level value(s) that values.yaml never declares: ` +
        `${readButUndeclared.join(', ')}. This is an invisible, undocumented setting — a consumer has no ` +
        `reference documenting that it exists, what it defaults to, or that it does anything at all.`,
    );
  }
  if (declaredButUnread.length) {
    parts.push(
      `values.yaml declares ${declaredButUnread.length} top-level key(s) that no template reads: ` +
        `${declaredButUnread.join(', ')}. This is a dead contract entry — during migration orphan detection ` +
        `it would cause a consumer's leftover key of the same name to be mis-classified as a legitimate, ` +
        `still-read value instead of an orphan.`,
    );
  }
  parts.push(
    'If this is deliberate (e.g. a parent-chart-supplied `global`), add the key to the allowlist in ' +
      'scripts/generate-skill.mjs.',
  );

  throw new Error(
    `Values contract drift between helm/helm-framework/templates/ and helm/helm-framework/values.yaml:\n\n${parts.join('\n\n')}`,
  );
}

export function updatePluginVersion(pluginJsonContent, version) {
  const plugin = JSON.parse(pluginJsonContent);
  plugin.version = version;
  return `${JSON.stringify(plugin, null, 2)}\n`;
}

function main() {
  const version = parseVersionArg(process.argv.slice(2));

  const chartYamlPath = join(REPO_ROOT, 'helm/helm-framework/Chart.yaml');
  const valuesYamlPath = join(REPO_ROOT, 'helm/helm-framework/values.yaml');
  const readmePath = join(REPO_ROOT, 'helm/helm-framework/README.md');
  const templatesDir = join(REPO_ROOT, 'helm/helm-framework/templates');
  const testChartYamlPath = join(REPO_ROOT, 'helm/helm-framework-test-template/Chart.yaml');
  const testValuesYamlPath = join(REPO_ROOT, 'helm/helm-framework-test-template/values.yaml');
  const testDeploymentPath = join(
    REPO_ROOT,
    'helm/helm-framework-test-template/templates/deployment.yaml',
  );

  const pluginDir = join(REPO_ROOT, 'plugins/helm-framework');
  const skillDir = join(pluginDir, 'skills/helm-framework');
  const resourcesDir = join(skillDir, 'resources');
  const pluginJsonPath = join(pluginDir, '.claude-plugin/plugin.json');
  const migrationSkillDir = join(pluginDir, 'skills/helm-framework-migration');
  const migrationResourcesDir = join(migrationSkillDir, 'resources');

  const chartName = extractChartName(readFileSync(chartYamlPath, 'utf8'));
  const sections = extractSections(readFileSync(valuesYamlPath, 'utf8'));
  const valuesTable = extractValuesTable(readFileSync(readmePath, 'utf8'));

  const valuesYamlContent = readFileSync(valuesYamlPath, 'utf8');
  const templateSources = readdirSync(templatesDir)
    .filter((name) => statSync(join(templatesDir, name)).isFile())
    .map((name) => readFileSync(join(templatesDir, name), 'utf8'));

  const readSet = extractValuesReadSet(templateSources);
  const valueTree = extractValueTree(valuesYamlContent);
  const declaredTopLevel = valueTree.filter((path) => !path.includes('.'));

  assertContractConsistency(readSet, declaredTopLevel, CONTRACT_ALLOWLIST);

  mkdirSync(resourcesDir, { recursive: true });
  mkdirSync(migrationResourcesDir, { recursive: true });

  writeFileSync(join(skillDir, 'SKILL.md'), buildSkillMarkdown({ chartName, version, sections }));

  writeFileSync(
    join(resourcesDir, 'values-reference.md'),
    `# ${chartName} values reference\n\nGenerated from \`helm/helm-framework/README.md\` (itself auto-generated by helm-docs). Do not edit by hand.\n\n${valuesTable}\n`,
  );

  writeFileSync(
    join(resourcesDir, 'example-chart.md'),
    buildExampleChartMarkdown({
      chartYaml: readFileSync(testChartYamlPath, 'utf8'),
      valuesYaml: readFileSync(testValuesYamlPath, 'utf8'),
      deploymentTemplate: readFileSync(testDeploymentPath, 'utf8'),
    }),
  );

  writeFileSync(pluginJsonPath, updatePluginVersion(readFileSync(pluginJsonPath, 'utf8'), version));

  writeFileSync(
    join(migrationSkillDir, 'SKILL.md'),
    buildMigrationSkillMarkdown({ chartName, version }),
  );

  writeFileSync(
    join(migrationResourcesDir, 'values-contract.md'),
    buildValuesContractMarkdown({ chartName, version, readSet, valueTree }),
  );

  writeFileSync(
    join(migrationResourcesDir, 'migration-playbook.md'),
    buildMigrationPlaybookMarkdown({ chartName, version }),
  );

  console.log(`Generated helm-framework skill for version ${version}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
