import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseVersionArg,
  extractChartName,
  extractSections,
  extractValuesTable,
  buildSkillMarkdown,
  buildExampleChartMarkdown,
  updatePluginVersion,
  extractValuesReadSet,
  extractValueTree,
  assertContractConsistency,
} from './generate-skill.mjs';

test('parseVersionArg reads the --version flag', () => {
  assert.equal(parseVersionArg(['--version', '1.2.3']), '1.2.3');
});

test('parseVersionArg throws when --version is missing', () => {
  assert.throws(() => parseVersionArg([]), /Usage: generate-skill\.mjs --version/);
});

test('parseVersionArg throws when --version has no value', () => {
  assert.throws(() => parseVersionArg(['--version']), /Usage: generate-skill\.mjs --version/);
});

test('extractChartName reads the name field from Chart.yaml', () => {
  const chartYaml = 'apiVersion: v2\nname: helm-framework\ndescription: x\n\ntype: library\n';
  assert.equal(extractChartName(chartYaml), 'helm-framework');
});

test('extractChartName throws when name is missing', () => {
  assert.throws(() => extractChartName('apiVersion: v2\n'), /Could not find "name:"/);
});

test('extractChartName strips surrounding quotes', () => {
  const chartYaml = 'apiVersion: v2\nname: "helm-framework-test-template"\n';
  assert.equal(extractChartName(chartYaml), 'helm-framework-test-template');
});

test('extractSections finds bracketed comment headers in values.yaml', () => {
  const values = [
    '# =============================================================================',
    '# GLOBAL CONFIGURATION',
    '# =============================================================================',
    'replicaCount: 1',
    '',
    '# =============================================================================',
    '# NETWORKING',
    '# =============================================================================',
    'service: {}',
  ].join('\n');
  assert.deepEqual(extractSections(values), ['GLOBAL CONFIGURATION', 'NETWORKING']);
});

test('extractSections returns an empty list when there are no headers', () => {
  assert.deepEqual(extractSections('replicaCount: 1\n'), []);
});

test('extractValuesTable slices from the "## Values" heading onward', () => {
  const readme = '# helm-framework\n\nSome intro.\n\n## Values\n\n| Key | Type |\n|-|-|\n';
  assert.equal(extractValuesTable(readme), '## Values\n\n| Key | Type |\n|-|-|');
});

test('extractValuesTable throws when README has no Values section', () => {
  assert.throws(() => extractValuesTable('# helm-framework\n'), /Could not find "## Values"/);
});

test('extractValuesTable drops the helm-docs footer', () => {
  const readme =
    '# helm-framework\n\n## Values\n\n| Key | Type |\n|-|-|\n\n----------------------------------------------\nAutogenerated from chart metadata using [helm-docs v1.14.2](https://example.com)\n';
  const table = extractValuesTable(readme);
  assert.equal(table, '## Values\n\n| Key | Type |\n|-|-|');
  assert.doesNotMatch(table, /Autogenerated/);
});

test('buildSkillMarkdown embeds the chart name, version, section list, and include pattern', () => {
  const md = buildSkillMarkdown({
    chartName: 'helm-framework',
    version: '1.2.3',
    sections: ['GLOBAL CONFIGURATION', 'NETWORKING'],
  });
  assert.match(md, /version: "1\.2\.3"/);
  assert.match(md, /- GLOBAL CONFIGURATION/);
  assert.match(md, /- NETWORKING/);
  assert.match(md, /helm-framework\.deployment\.global/);
  assert.match(md, /^---\nname: "helm-framework"/);
});

test('buildExampleChartMarkdown embeds all three file contents', () => {
  const md = buildExampleChartMarkdown({
    chartYaml: 'name: helm-framework-test-template\n',
    valuesYaml: 'replicaCount: 1\n',
    deploymentTemplate: '{{ include "helm-framework.deployment.global" . }}\n',
  });
  assert.match(md, /name: helm-framework-test-template/);
  assert.match(md, /replicaCount: 1/);
  assert.match(md, /helm-framework\.deployment\.global/);
});

test('updatePluginVersion sets version and preserves other fields', () => {
  const input = JSON.stringify({ name: 'helm-framework', description: 'x', version: '0.0.0' });
  const output = updatePluginVersion(input, '1.2.3');
  const parsed = JSON.parse(output);
  assert.equal(parsed.version, '1.2.3');
  assert.equal(parsed.name, 'helm-framework');
  assert.equal(parsed.description, 'x');
  assert.ok(output.endsWith('\n'));
});

// --- extractValuesReadSet -----------------------------------------------

test('extractValuesReadSet finds top-level .Values.X names across sources', () => {
  const sources = [
    '{{ .Values.replicaCount }}\n{{ .Values.image.repository }}',
    '{{- if .Values.ingress.enabled }}\n{{ .Values.service.port }}\n{{- end }}',
  ];
  assert.deepEqual(extractValuesReadSet(sources), ['image', 'ingress', 'replicaCount', 'service']);
});

test('extractValuesReadSet dedupes repeated reads and sorts the result', () => {
  const sources = ['{{ .Values.envVars }}{{ .Values.envVars }}', '{{ .Values.appSettings }}'];
  assert.deepEqual(extractValuesReadSet(sources), ['appSettings', 'envVars']);
});

test('extractValuesReadSet accepts a single concatenated string', () => {
  const combined = '{{ .Values.replicaCount }}\n{{ .Values.image.repository }}';
  assert.deepEqual(extractValuesReadSet(combined), ['image', 'replicaCount']);
});

test('extractValuesReadSet cannot see reads that go through helper indirection', () => {
  // A helper like `include "helm-framework.values.service.port"` reads
  // .Values.service.port internally, but the literal string never appears
  // in the calling template — this is exactly the incompleteness that
  // makes nested paths non-authoritative.
  const sources = [
    '{{ include "helm-framework.values.service.port" . }}\n{{ .Values.service }}',
  ];
  assert.deepEqual(extractValuesReadSet(sources), ['service']);
});

// --- extractValueTree -----------------------------------------------------

test('extractValueTree derives nested dotted paths from indentation', () => {
  const values = ['image:', '  repository: alpine', '  tag: "1.0"', 'service:', '  port: 80'].join(
    '\n',
  );
  assert.deepEqual(extractValueTree(values), [
    'image',
    'image.repository',
    'image.tag',
    'service',
    'service.port',
  ]);
});

test('extractValueTree skips blank lines and comments', () => {
  const values = [
    '# -- a comment above a key',
    'image:',
    '',
    '  # a comment inside the map',
    '  repository: alpine',
  ].join('\n');
  assert.deepEqual(extractValueTree(values), ['image', 'image.repository']);
});

test('extractValueTree does not descend into list items', () => {
  const values = [
    'ingress:',
    '  hosts:',
    '    - host: example.com',
    '      paths:',
    '        - path: /',
    '  tls: []',
  ].join('\n');
  assert.deepEqual(extractValueTree(values), ['ingress', 'ingress.hosts', 'ingress.tls']);
});

test('extractValueTree resumes normal parsing after a list ends', () => {
  const values = ['jobs:', '  - name: migrate', '    args: []', 'sidecars: []'].join('\n');
  assert.deepEqual(extractValueTree(values), ['jobs', 'sidecars']);
});

// --- assertContractConsistency --------------------------------------------

test('assertContractConsistency passes when read and declared sets match', () => {
  assert.doesNotThrow(() =>
    assertContractConsistency(['image', 'service'], ['image', 'service']),
  );
});

test('assertContractConsistency throws when a template reads an undeclared value', () => {
  assert.throws(
    () => assertContractConsistency(['image', 'ghostValue'], ['image']),
    /ghostValue/,
  );
});

test('assertContractConsistency throws when a declared value is never read', () => {
  assert.throws(
    () => assertContractConsistency(['image'], ['image', 'deadKey']),
    /deadKey/,
  );
});

test('assertContractConsistency allowlist exempts keys in both directions', () => {
  assert.doesNotThrow(() =>
    assertContractConsistency(['image', 'global'], ['image'], ['global']),
  );
  assert.doesNotThrow(() =>
    assertContractConsistency(['image'], ['image', 'global'], ['global']),
  );
});

