name: Docs

on:
  push:
    branches: [main]
    paths:
      - "helm/**"
      - "README.md"
      - "CONTRIBUTING.md"

permissions:
  contents: write

jobs:
  generate-docs:
    name: Generate Helm Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v2
        with:
          chart-search-root: helm/helm-framework
          output-file: README.md

      - name: Commit docs changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate helm-docs"
          file_pattern: "helm/helm-framework/README.md"
